### ISSUE TITLE
Document merging spike

### ISSUE THREAD

**Issue by 20jasper** [web-dev-cody-hackathon/100editors#22]
Figure out a good way to merge data from multiple users at once

Automerge looks like a good solution, but there might be a better one

**Comment by alcpereira** [comment]
There is this one too :
https://github.com/yjs/yjs

**Comment by Katherine29a** [comment]
Here's a list of some emerging data tools from multiple users simultaneously:

1. **ShareDB:** ShareDB, as mentioned previously, is a real-time database that supports collaborative data synchronization. It's particularly suitable for web and mobile applications. Link: https://github.com/share/sharedb

2. **SwarmJS:** SwarmJS is a JavaScript library that provides synchronization and conflict resolution for collaborative applications. It's designed to work with various data types and is suitable for real-time collaborative text editors and more. Link: https://github.com/gritzko/swarm

3. **GUN:** GUN is a decentralized, real-time, offline-first database that can be used to build collaborative applications. It supports peer-to-peer data synchronization and conflict resolution. Link: https://github.com/amark/gun

4. **RethinkDB:** RethinkDB is a distributed NoSQL database that offers real-time change feeds, making it suitable for building collaborative applications where data changes need to be synchronized in real-time.  Link: https://github.com/rethinkdb/rethinkdb

6. **PeerJS:** PeerJS is a JavaScript library for building peer-to-peer applications that can be used for real-time collaborative features, including file sharing and text editing. Link: https://github.com/peers/peerjs
