### ISSUE TITLE
Hosting Spike

### ISSUE THREAD

**Issue by 20jasper** [web-dev-cody-hackathon/100editors#4]
Where do we want to host the app?

I'm familiar with railway, but I'm not entirely sure if it allow teams. Would we be OK if deployment happens automatically and not all members have access?

**Comment by alcpereira** [comment]
Vercel is usually the go-to solution for Next. Feel free to investigate its features/limitations.

**Comment by windyScripts** [comment]
Cyclic would be another option, though I'm inclined towards Vercel as well.

**Comment by alcpereira** [comment]
Vercel deployment is done, including PR preview deployments. Feel free to reopen the issue if you have some questions or concerns regarding the solution.
