### ISSUE TITLE
Editor Spike

### ISSUE THREAD

**Issue by 20jasper** [web-dev-cody-hackathon/100editors#8]
Do we even need an editor? Can we just use plain text in a textarea?

    Quill: Quill is a popular rich text editor library that offers real-time collaborative editing capabilities. It can be extended with the Quill-collaborative module to enable simultaneous editing and feedback.
    ProseMirror: ProseMirror is a highly customizable and extensible text editor library that supports real-time collaboration through various plugins and extensions. It's a versatile choice for building collaborative text editing features.
    Conclave: Conclave is a real-time collaboration and document editing platform. It provides a set of APIs and tools to integrate collaborative features into your web app, including real-time editing, comments, and suggestions.
    Etherpad: Etherpad is an open-source collaborative editing platform that can be integrated into your app. It offers real-time text editing with features like collaborative cursors and chat.
    CKEditor Collaboration Plugin: If you're using CKEditor as your text editor, consider adding the CKEditor Collaboration Plugin. It extends CKEditor to provide real-time collaborative editing capabilities.

**Comment by alcpereira** [comment]
Feel free to double check those lists:
https://github.com/JefMari/awesome-wysiwyg-editors#for-react
https://github.com/topics/editor

**Comment by windyScripts** [comment]
> https://github.com/JefMari/awesome-wysiwyg-editors#for-react

Found [this textarea based react editor](https://github.com/inokawa/rich-textarea) interesting.
[Draftjs](https://github.com/facebookarchive/draft-js) also looks promising.

**Comment by 20jasper** [comment]
Ckeditor has the feature we're looking for, but you need to pay for it
Quill has change deltas, so it looks the most promising out of these so far

**Comment by alcpereira** [comment]
I forgot to mention Lexical which has been open-sourced by Facebook and is out of the box compatible with React and designed to be collaborative.
Let's continue with Quill but if we need to pivot, we should consider this option.
